id: PFF6FD7CD
initial_creation_type: ocr
source_metadata:
  volumes:
    0db4b162ba2746feb9d258199cb8e259:
      base_file: v040.txt
      image_group_id: I1PD95885
      title: འཕགས་མ་དུག་སེལ་བའི་སྒྲུབ་ཐབས།
      total_pages: 1648
      volume_number: 40
