id: D47E9990E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-04-18T11:14:57+00:00'
last_modified: '2022-05-26T14:06:12.300953+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    4ca4:
      image_group_id: I1PD95885
      title: འཕགས་མ་དུག་སེལ་བའི་སྒྲུབ་ཐབས།
      total_pages: 1648
      order: 40
      base_file: 4ca4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
